### ISSUE TITLE
Models are not available for download

### ISSUE THREAD

**Issue by Varat7v2** [cftang0827/pedestrian_recognition#10]
@cftang0827 Hi, the model download link you have shared are not traceable. Can you please check. Thank you.

**Comment by Xrenya** [comment]
@cftang0827 do you still have the pre-trained models?

**Comment by cftang0827** [comment]
Sorry for the late reply, here is the update with model detail
thanks for the issue
https://github.com/cftang0827/pedestrian_recognition/pull/11
