### ISSUE TITLE
Mobilenet backbone download link not working

### ISSUE THREAD

**Issue by FerreJanssen** [cftang0827/pedestrian_recognition#13]
@cftang0827 The google drive link to your mobilenet backbone model is no longer working. Do you still have this model?

**Comment by cftang0827** [comment]
I just updated the model link, please have a look. Thanks
```sh
wget https://drive.google.com/u/0/uc?id=0B3gersZ2cHIxVFI1Rjd5aDgwOG8&export=download -O model/MobileNetSSD_deploy.caffemodel

```

**Comment by FerreJanssen** [comment]
> I just updated the model link, please have a look. Thanks
> 
> ```shell
> wget https://drive.google.com/u/0/uc?id=0B3gersZ2cHIxVFI1Rjd5aDgwOG8&export=download -O model/MobileNetSSD_deploy.caffemodel
> ```

is this the model used for extracting human feature embeddings?

**Comment by cftang0827** [comment]
No, in this project there are two steps, the first one is to extract human bounding box, then use that human picture to generate vector.

**Comment by cftang0827** [comment]
Please have a look about README file.

**Comment by FerreJanssen** [comment]
Okay sorry I misunderstood. I thought you retrained the triplet loss network with mobilenet as a backbone instead of ResNet. Thanks for your help.
