### ISSUE TITLE
Readme: Download file not found 

### ISSUE THREAD

**Issue by muka** [cftang0827/pedestrian_recognition#4]
Hi,
while trying to test your implementation I noticed the readme is out of date. 

In `Workflow` section, point one has link which return 404.

Is the resource still available?

Thanks

**Comment by cftang0827** [comment]
Hi @muka, thanks for letting me know the issue.
I had already updated the latest version of README, please take a look. If there's any problem, please let me know. Thank you. 🙏

**Comment by muka** [comment]
Thank you very much!
