### ISSUE TITLE
crop_human extracts 0 height/width frame if x or y are negative

### ISSUE THREAD

**Issue by TiFu** [cftang0827/pedestrian_recognition#6]
Hi!

Thanks for providing the weights & this model. It works amazingly well. 

I noticed that sometimes the person detection emits bounding boxes with points minimally outside the image (e.g. [[(580, -2), (1271, 715)]]). 

If you then call `crop_human`, it seems like the slice operator doesn't properly work with negative numbers:

```
Cropping image: Left Bottom (580, -2) /  Right Top (1271, 715)
Subframe: (0, 691, 3)
``` 
=> 0 width frame

I'd probably fix this by introducing  `max(0, detectionCoordinate)` in `human_locations` during the scaling of the object location. Happy to provide a PR with the fix. 

Cheers
Tino

**Comment by cftang0827** [comment]
Hi, thank you for your information. It’s really great to have your pull requests.
